/**
 * MediKiosk Patient Kiosk Configuration & 100% Centralized Multilingual I18N Dictionary
 */
export const CONFIG = {
    APP_NAME: "MediKiosk",
    HOSPITAL_NAME: "All India Institute of Ayurveda & Associated Hospitals",
    API_BASE_URL: window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1" 
        ? "http://localhost:8000/api/v1" 
        : "https://medikiosk-backend-ddbm.onrender.com/api/v1",
    WS_TRIAGE_URL: window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1"
        ? "ws://localhost:8000/api/v1/triage/ws"
        : "wss://medikiosk-backend-ddbm.onrender.com/api/v1/triage/ws",
    
    // Inactivity Timers (in milliseconds)
    INACTIVITY_WARN_MS: 150000,    // 2.5 Minutes
    INACTIVITY_TIMEOUT_MS: 180000, // 3.0 Minutes
    
    // Supported Regional Languages (English default + 7 Regional)
    LANGUAGES: [
        { code: "en", name: "English", script: "Latin", nativeVoice: "en-IN" },
        { code: "hi", name: "हिन्दी", script: "Devanagari", nativeVoice: "hi-IN" },
        { code: "pa", name: "ਪੰਜਾਬੀ", script: "Gurmukhi", nativeVoice: "pa-IN" },
        { code: "bn", name: "বাংলা", script: "Bengali", nativeVoice: "bn-IN" },
        { code: "ta", name: "தமிழ்", script: "Tamil", nativeVoice: "ta-IN" },
        { code: "te", name: "తెలుగు", script: "Telugu", nativeVoice: "te-IN" },
        { code: "mr", name: "मराठी", script: "Devanagari", nativeVoice: "mr-IN" },
        { code: "gu", name: "ગુજરાતી", script: "Gujarati", nativeVoice: "gu-IN" }
    ],

    // Complete Centralized UI Dictionary for 100% Consistent Multilingual Translations
    I18N: {
        hi: {
            appName: "मेडीकियोस्क",
            hospitalName: "अखिल भारतीय आयुर्वेद संस्थान (AIIA) एवं संबद्ध अस्पताल",
            govtTag: "आयुष मंत्रालय एवं स्वास्थ्य व परिवार कल्याण मंत्रालय • भारत सरकार",
            contrast: "उच्च कंट्रास्ट",
            textSize: "अक्षर आकार",
            soundOn: "ध्वनि चालू",
            soundOff: "ध्वनि म्यूट",
            repeatQuestion: "प्रश्न दोबारा सुनें",
            slowSpeech: "धीमी आवाज़",
            needMoreTime: "मुझे और समय चाहिए",
            emergencyHelp: "आपातकालीन सहायता",
            
            // Screen 1: Auth
            authTitle: "मरीज लॉगिन एवं पंजीकरण",
            authSub: "ओपीडी पूर्व-परामर्श जांच शुरू करने के लिए कृपया अपनी पहचान सत्यापित करें",
            abhaLoginBtn: "आभा (ABHA) आईडी से लॉगिन / पंजीकरण",
            phoneLoginBtn: "मोबाइल नंबर एवं एमपिन (MPIN)",
            walkinBtn: "त्वरित वॉक-इन पर्ची (अतिथि मरीज)",
            walkinSub: "बिना किसी पूर्व आईडी के तुरंत ओपीडी परामर्श शुरू करें",
            abhaCardScan: "आभा कार्ड क्यूआर स्कैन करें",
            enterPhonePlaceholder: "10-अंकीय मोबाइल नंबर दर्ज करें",
            enterNamePlaceholder: "मरीज का पूरा नाम दर्ज करें",
            startWalkinBtn: "सीधे आगे बढ़ें ➔",

            // Screen 2: Discipline Select
            welcomePatient: "नमस्ते",
            disciplineSelectTitle: "अपनी परामर्श प्रणाली चुनें",
            disciplineSelectSub: "कृपया आधुनिक चिकित्सा या आयुर्वेद ओपीडी का चयन करें",
            allopathyTitle: "आधुनिक चिकित्सा (एलोपैथी)",
            allopathyDesc: "जनरल मेडिसिन, कार्डियोलॉजी, ऑर्थोपेडिक्स, गैस्ट्रो, डर्मेटोलॉजी। मानक सोक्रेट्स (SOCRATES) 7-चरणीय लक्षण जांच।",
            allopathyBadge: "SOCRATES नैदानिक प्रोटोकॉल",
            ayushTitle: "आयुर्वेद एवं आयुष ओपीडी",
            ayushDesc: "कायाचिकित्सा, पंचकर्म, शल्य तंत्र, अग्नि एवं त्वचा रोग। शास्त्रीय दशविध परीक्षा एवं आहार-विहार मूल्यांकन।",
            ayushBadge: "दशविध परीक्षा एवं आयुष प्रोटोकॉल",

            // Screen 3: Body Map
            bodyMapTitle: "तकलीफ़ का मुख्य स्थान चुनें",
            bodyMapSub: "शरीर के उस अंग पर स्पर्श करें जहां आपको दर्द या लक्षण महसूस हो रहे हैं",

            // Screen 4: Voice Dialogue
            stepLabel: "चरण",
            ofLabel: "का",
            speakOrTap: "माइक पर बोलें या नीचे दिए गए विकल्पों को स्पर्श करें",
            listening: "सुन रहे हैं... बोलिए",
            recordingDone: "रिकॉर्डिंग पूर्ण",
            liveStreaming: "लाइव रिकॉर्डिंग",
            prevBtn: "पिछला",
            nextBtn: "अगला ➔",
            confirmBtn: "पुष्टि करें ➔",

            // Screen 5: OCR
            ocrTitle: "पुरानी पर्ची या जांच रिपोर्ट स्कैन करें (वैकल्पिक)",
            ocrSub: "दस्तावेज़ को कैमरे के सामने रखें और फोटो खींचें",
            skipOcr: "कोई रिपोर्ट नहीं (आगे बढ़ें)",
            captureBtn: "फोटो खींचें एवं जांचें",

            // Screen 6: Completion Decision
            completionTitle: "स्वास्थ्य मूल्यांकन पूर्ण हुआ!",
            completionSub: "कृपया चुनें कि आप यह जानकारी कैसे सहेजना चाहते हैं:",
            choiceAccountOnlyTitle: "केवल मेरे स्वास्थ्य खाते (ABHA) में सहेजें",
            choiceAccountOnlyDesc: "यह रिपोर्ट आपके डिजिटल स्वास्थ्य लॉकर में सुरक्षित हो जाएगी। कोई अस्पताल पर्ची जारी नहीं होगी।",
            choiceParchiTitle: "खाते में सहेजें एवं डिजिटल ओपीडी पर्ची (टोकन) बनाएं",
            choiceParchiDesc: "आपके लिए अस्पताल की लाइव कतार में टोकन नंबर, कमरा नंबर और डिजिटल पर्ची बनाई जाएगी।",
            proceedBtn: "आगे बढ़ें ➔",

            // Screen 7: Hospital Selector
            selectHospitalTitle: "आप इस समय किस अस्पताल में हैं?",
            selectHospitalSub: "संबद्ध नेटवर्क अस्पतालों में से अपना वर्तमान अस्पताल चुनें:",
            confirmHospitalBtn: "अस्पताल चुनें एवं पर्ची बनाएं ➔",

            // Screen 8: Digital Parchi
            parchiSuccess: "पंजीकरण सफल! अपनी ओपीडी पर्ची प्राप्त करें",
            parchiWait: "कृपया अपनी टोकन पर्ची लेकर निर्दिष्ट कमरे के बाहर प्रतीक्षा करें।",
            tokenLabel: "आपका टोकन नंबर",
            deptLabel: "विभाग",
            roomLabel: "कमरा नंबर",
            waitLabel: "अनुमानित प्रतीक्षा समय",
            signedQrTag: "डिजिटल रूप से हस्ताक्षरित एंटी-टैम्पर टोकन",
            printBtn: "पर्ची प्रिंट करें",
            homeBtn: "समाप्त करें एवं होम पर जाएं ➔"
        },
        en: {
            appName: "MediKiosk",
            hospitalName: "All India Institute of Ayurveda & Associated Hospitals",
            govtTag: "Ministry of Ayush & MoHFW • Government of India",
            contrast: "High Contrast",
            textSize: "Text Size",
            soundOn: "Sound ON",
            soundOff: "Sound Muted",
            repeatQuestion: "Repeat Question",
            slowSpeech: "Slow Speech",
            needMoreTime: "I Need More Time",
            emergencyHelp: "EMERGENCY HELP",
            
            // Screen 1: Auth
            authTitle: "Patient Authentication & Registration",
            authSub: "Verify your identity or choose quick guest walk-in to start clinical intake",
            abhaLoginBtn: "Login / Register with ABHA ID (ABDM)",
            phoneLoginBtn: "Mobile Number & MPIN",
            walkinBtn: "Quick Guest Walk-in (No ID Required)",
            walkinSub: "Start consultation immediately with an instant ephemeral profile",
            abhaCardScan: "Scan Physical ABHA Card QR",
            enterPhonePlaceholder: "Enter 10-digit mobile number",
            enterNamePlaceholder: "Enter patient full name",
            startWalkinBtn: "Proceed Directly ➔",

            // Screen 2: Discipline Select
            welcomePatient: "Welcome",
            disciplineSelectTitle: "Select Clinical Consultation Discipline",
            disciplineSelectSub: "Choose between Modern Allopathic Medicine or Ayurvedic OPD",
            allopathyTitle: "Modern Medicine (Allopathy)",
            allopathyDesc: "General Medicine, Cardiology, Orthopedics, Gastroenterology, Dermatology. Standard 7-step SOCRATES exploration.",
            allopathyBadge: "SOCRATES Clinical Protocol",
            ayushTitle: "Ayurveda & AYUSH OPD",
            ayushDesc: "Kayachikitsa, Panchakarma, Shalya Tantra, Agni & Twak Roga. Classical Dashavidha Pariksha & Ahara-Vihara evaluation.",
            ayushBadge: "Dashavidha Pariksha Protocol",

            // Screen 3: Body Map
            bodyMapTitle: "Select Affected Body Region",
            bodyMapSub: "Tap on the anatomical region where you feel pain, discomfort, or symptoms",

            // Screen 4: Voice Dialogue
            stepLabel: "Step",
            ofLabel: "of",
            speakOrTap: "Speak into the microphone or tap the quick options below",
            listening: "Listening... please speak now",
            recordingDone: "Recording complete",
            liveStreaming: "LIVE STREAMING",
            prevBtn: "Previous",
            nextBtn: "Next ➔",
            confirmBtn: "Confirm & Proceed ➔",

            // Screen 5: OCR
            ocrTitle: "Scan Previous Prescription or Lab Report (Optional)",
            ocrSub: "Hold document in front of camera and tap capture",
            skipOcr: "No Prior Reports (Skip)",
            captureBtn: "Capture & Extract",

            // Screen 6: Completion Decision
            completionTitle: "Clinical Intake Completed!",
            completionSub: "Please choose how you would like to proceed with this record:",
            choiceAccountOnlyTitle: "Save to My Health Account Only (ABHA Locker)",
            choiceAccountOnlyDesc: "Saves clinical summary to your personal digital record without generating an active queue token.",
            choiceParchiTitle: "Save to Account & Generate Digital OPD Parchi (Token)",
            choiceParchiDesc: "Issues an official queue token, assigns OPD room, and sends digital case sheet to duty physician.",
            proceedBtn: "Continue ➔",

            // Screen 7: Hospital Selector
            selectHospitalTitle: "Which hospital are you currently visiting?",
            selectHospitalSub: "Select your active hospital from the linked national health network:",
            confirmHospitalBtn: "Select Hospital & Generate Parchi ➔",

            // Screen 8: Digital Parchi
            parchiSuccess: "Intake Complete! Please Take Your Token",
            parchiWait: "Please proceed to your assigned OPD room. Your digital case sheet is ready for the doctor.",
            tokenLabel: "YOUR TOKEN NUMBER",
            deptLabel: "Department",
            roomLabel: "Assigned Room",
            waitLabel: "Estimated Wait Time",
            signedQrTag: "Cryptographically Signed Anti-Tamper QR",
            printBtn: "Print Token Slip",
            homeBtn: "Finish & Return Home ➔"
        },
        pa: {
            appName: "ਮੈਡੀਕਿਓਸਕ",
            hospitalName: "ਆਲ ਇੰਡੀਆ ਇੰਸਟੀਚਿਊਟ ਆਫ਼ ਆਯੁਰਵੇਦ ਅਤੇ ਸੰਬੰਧਿਤ ਹਸਪਤਾਲ",
            govtTag: "ਆਯੁਸ਼ ਮੰਤਰਾਲਾ ਅਤੇ ਸਿਹਤ ਮੰਤਰਾਲਾ • ਭਾਰਤ ਸਰਕਾਰ",
            contrast: "ਹਾਈ ਕੰਟ੍ਰਾਸਟ",
            textSize: "ਅੱਖਰਾਂ ਦਾ ਆਕਾਰ",
            soundOn: "ਆਵਾਜ਼ ਚਾਲੂ",
            soundOff: "ਆਵਾਜ਼ ਬੰਦ",
            repeatQuestion: "ਸਵਾਲ ਦੁਬਾਰਾ ਸੁਣੋ",
            slowSpeech: "ਹੌਲੀ ਆਵਾਜ਼",
            needMoreTime: "ਹੋਰ ਸਮਾਂ ਚਾਹੀਦਾ ਹੈ",
            emergencyHelp: "ਐਮਰਜੈਂਸੀ ਸਹਾਇਤਾ",
            authTitle: "ਮਰੀਜ਼ ਲੌਗਇਨ ਅਤੇ ਰਜਿਸਟ੍ਰੇਸ਼ਨ",
            authSub: "ਓਪੀਡੀ ਜਾਂਚ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੀ ਪਛਾਣ ਦਰਜ ਕਰੋ",
            abhaLoginBtn: "ਆਭਾ (ABHA) ਆਈ.ਡੀ. ਨਾਲ ਲੌਗਇਨ / ਰਜਿਸਟਰ ਕਰੋ",
            phoneLoginBtn: "ਮੋਬਾਈਲ ਨੰਬਰ ਅਤੇ ਐਮਪਿਨ",
            walkinBtn: "ਤੁਰੰਤ ਵਾਕ-ਇਨ ਪਰਚੀ (ਮਹਿਮਾਨ ਮਰੀਜ਼)",
            walkinSub: "ਬਿਨਾਂ ਕਿਸੇ ਆਈਡੀ ਦੇ ਤੁਰੰਤ ਓਪੀਡੀ ਜਾਂਚ ਸ਼ੁਰੂ ਕਰੋ",
            abhaCardScan: "ਆਭਾ ਕਾਰਡ ਸਕੈਨ ਕਰੋ",
            enterPhonePlaceholder: "10-ਅੰਕਾਂ ਦਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ",
            enterNamePlaceholder: "ਮਰੀਜ਼ ਦਾ ਪੂਰਾ ਨਾਮ",
            startWalkinBtn: "ਅੱਗੇ ਵਧੋ ➔",
            welcomePatient: "ਜੀ ਆਇਆਂ ਨੂੰ",
            disciplineSelectTitle: "ਆਪਣਾ ਓ.ਪੀ.ਡੀ. ਸਿਸਟਮ ਚੁਣੋ",
            disciplineSelectSub: "ਕਿਰਪਾ ਕਰਕੇ ਐਲੋਪੈਥੀ ਜਾਂ ਆਯੁਰਵੇਦ ਓਪੀਡੀ ਦੀ ਚੋਣ ਕਰੋ",
            allopathyTitle: "ਐਲੋਪੈਥੀ (ਆਧੁਨਿਕ ਦਵਾਈ)",
            allopathyDesc: "ਜਨਰਲ ਮੈਡੀਸਨ, ਕਾਰਡੀਓਲੋਜੀ, ਹੱਡੀਆਂ, ਪੇਟ ਅਤੇ ਚਮੜੀ ਰੋਗ।",
            allopathyBadge: "SOCRATES ਪ੍ਰੋਟੋਕੋਲ",
            ayushTitle: "ਆਯੁਰਵੇਦ ਅਤੇ ਆਯੁਸ਼ ਓ.ਪੀ.ਡੀ.",
            ayushDesc: "ਕਾਯਾਚਿਕਿਤਸਾ, ਪੰਚਕਰਮਾ, ਸ਼ਲਿਆ ਤੰਤਰ ਅਤੇ ਅਗਨੀ ਚਿਕਿਤਸਾ।",
            ayushBadge: "ਦਸ਼ਵਿਧ ਪਰੀਖਿਆ ਪ੍ਰੋਟੋਕੋਲ",
            bodyMapTitle: "ਦਰਦ ਦਾ ਮੁੱਖ ਅੰਗ ਚੁਣੋ",
            bodyMapSub: "ਸਰੀਰ ਦੇ ਉਸ ਅੰਗ 'ਤੇ ਟੈਪ ਕਰੋ ਜਿੱਥੇ ਤਕਲੀਫ਼ ਹੈ",
            stepLabel: "ਕਦਮ",
            ofLabel: "ਦਾ",
            speakOrTap: "ਮਾਈਕ 'ਤੇ ਬੋਲੋ ਜਾਂ ਹੇਠਾਂ ਦਿੱਤੇ ਵਿਕਲਪਾਂ ਨੂੰ ਚੁਣੋ",
            listening: "ਸੁਣ ਰਹੇ ਹਾਂ... ਬੋਲੋ",
            recordingDone: "ਰਿਕਾਰਡਿੰਗ ਪੂਰੀ",
            liveStreaming: "ਲਾਈਵ ਰਿਕਾਰਡਿੰਗ",
            prevBtn: "ਪਿੱਛੇ",
            nextBtn: "ਅਗਲਾ ➔",
            confirmBtn: "ਪੁਸ਼ਟੀ ਕਰੋ ➔",
            ocrTitle: "ਪੁਰਾਣੀ ਪਰਚੀ ਜਾਂ ਰਿਪੋਰਟ ਸਕੈਨ ਕਰੋ",
            ocrSub: "ਕੈਮਰੇ ਅੱਗੇ ਦਸਤਾਵੇਜ਼ ਰੱਖੋ",
            skipOcr: "ਕੋਈ ਰਿਪੋਰਟ ਨਹੀਂ (ਛੱਡੋ)",
            captureBtn: "ਫੋਟੋ ਖਿੱਚੋ",
            completionTitle: "ਜਾਂਚ ਪੂਰੀ ਹੋਈ!",
            completionSub: "ਕਿਰਪਾ ਕਰਕੇ ਚੁਣੋ ਕਿ ਤੁਸੀਂ ਇਹ ਜਾਣਕਾਰੀ ਕਿਵੇਂ ਸਾਂਭਣੀ ਚਾਹੁੰਦੇ ਹੋ:",
            choiceAccountOnlyTitle: "ਸਿਰਫ਼ ਮੇਰੇ ਸਿਹਤ ਖਾਤੇ (ABHA) ਵਿੱਚ ਸਾਂਭੋ",
            choiceAccountOnlyDesc: "ਰਿਪੋਰਟ ਤੁਹਾਡੇ ਡਿਜੀਟਲ ਲਾਕਰ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਹੋਵੇਗੀ।",
            choiceParchiTitle: "ਖਾਤੇ ਵਿੱਚ ਸਾਂਭੋ ਅਤੇ ਡਿਜੀਟਲ ਓਪੀਡੀ ਪਰਚੀ ਬਣਾਓ",
            choiceParchiDesc: "ਹਸਪਤਾਲ ਵਿੱਚ ਲਾਈਵ ਕਤਾਰ ਲਈ ਟੋਕਨ ਅਤੇ ਕਮਰਾ ਨੰਬਰ ਜਾਰੀ ਹੋਵੇਗਾ।",
            proceedBtn: "ਅੱਗੇ ਵਧੋ ➔",
            selectHospitalTitle: "ਤੁਸੀਂ ਇਸ ਸਮੇਂ ਕਿਸ ਹਸਪਤਾਲ ਵਿੱਚ ਹੋ?",
            selectHospitalSub: "ਸੰਬੰਧਿਤ ਹਸਪਤਾਲਾਂ ਵਿੱਚੋਂ ਆਪਣਾ ਹਸਪਤਾਲ ਚੁਣੋ:",
            confirmHospitalBtn: "ਹਸਪਤਾਲ ਚੁਣੋ ਅਤੇ ਪਰਚੀ ਬਣਾਓ ➔",
            parchiSuccess: "ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਸਫਲ! ਆਪਣੀ ਪਰਚੀ ਲਵੋ",
            parchiWait: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਨਿਰਧਾਰਤ ਕਮਰੇ ਦੇ ਬਾਹਰ ਉਡੀਕ ਕਰੋ।",
            tokenLabel: "ਤੁਹਾਡਾ ਟੋਕਨ ਨੰਬਰ",
            deptLabel: "ਵਿਭਾਗ",
            roomLabel: "ਕਮਰਾ ਨੰਬਰ",
            waitLabel: "ਅੰਦਾਜ਼ਨ ਉਡੀਕ ਸਮਾਂ",
            signedQrTag: "ਡਿਜੀਟਲ ਹਸਤਾਖਰਿਤ ਟੋਕਨ",
            printBtn: "ਪਰਚੀ ਪ੍ਰਿੰਟ ਕਰੋ",
            homeBtn: "ਸਮਾਪਤ ਕਰੋ ➔"
        },
        bn: {
            appName: "মেডিকিয়স্ক",
            hospitalName: "অল ইন্ডিয়া ইনস্টিটিউট অফ আয়ুর্বেদ ও সংশ্লিষ্ট হাসপাতাল",
            govtTag: "আয়ুষ মন্ত্রক ও স্বাস্থ্য মন্ত্রক • ভারত সরকার",
            contrast: "উচ্চ বৈসাদৃশ্য",
            textSize: "অক্ষরের আকার",
            soundOn: "শব্দ চালু",
            soundOff: "শব্দ বন্ধ",
            repeatQuestion: "প্রশ্নটি পুনরায় শুনুন",
            slowSpeech: "ধীর গতি",
            needMoreTime: "আরও সময় প্রয়োজন",
            emergencyHelp: "জরুরি সহায়তা",
            authTitle: "রোগী লগইন ও নিবন্ধন",
            authSub: "পরামর্শ শুরু করতে নিজের পরিচয় যাচাই করুন",
            abhaLoginBtn: "আভা (ABHA) আইডি দিয়ে লগইন / নিবন্ধন",
            phoneLoginBtn: "মোবাইল নম্বর ও এমপিন",
            walkinBtn: "দ্রুত ওয়াক-ইন রেজিস্ট্রেশন",
            walkinSub: "তাত্ক্ষণিক অস্থায়ী প্রোফাইল দিয়ে শুরু করুন",
            abhaCardScan: "আভা কার্ড কিউআর স্ক্যান",
            enterPhonePlaceholder: "১০-সংখ্যার মোবাইল নম্বর লিখুন",
            enterNamePlaceholder: "রোগীর সম্পূর্ণ নাম",
            startWalkinBtn: "এগিয়ে যান ➔",
            welcomePatient: "স্বাগতম",
            disciplineSelectTitle: "পরামর্শ ব্যবস্থা নির্বাচন করুন",
            disciplineSelectSub: "এলোপ্যাথি অথবা আয়ুর্বেদ ওপিডি নির্বাচন করুন",
            allopathyTitle: "আধুনিক চিকিৎসা (এলোপ্যাথি)",
            allopathyDesc: "জেনারেল মেডিসিন, হৃদরোগ, অস্থি ও চর্মরোগ।",
            allopathyBadge: "SOCRATES প্রোটোকল",
            ayushTitle: "আয়ুর্বেদ ও আয়ুষ ওপিডি",
            ayushDesc: "কায়াচিকিৎসা, পঞ্চকর্ম, শল্য তন্ত্র ও অগ্নি চিকিৎসা।",
            ayushBadge: "দশবিধ পরীক্ষা প্রোটোকল",
            bodyMapTitle: "অসুস্থতার প্রধান স্থান নির্বাচন করুন",
            bodyMapSub: "শরীরের যে অংশে ব্যথা আছে সেখানে স্পর্শ করুন",
            stepLabel: "ধাপ",
            ofLabel: "এর",
            speakOrTap: "মাইকে কথা বলুন বা নীচের বিকল্পগুলি স্পর্শ করুন",
            listening: "শুনছি... বলুন",
            recordingDone: "রেকর্ডিং সম্পন্ন",
            liveStreaming: "লাইভ রেকর্ডিং",
            prevBtn: "পূর্ববর্তী",
            nextBtn: "পরবর্তী ➔",
            confirmBtn: "নিশ্চিত করুন ➔",
            ocrTitle: "পুরানো প্রেসক্রিপশন বা রিপোর্ট স্ক্যান করুন",
            ocrSub: "ক্যামেরার সামনে নথিটি রাখুন",
            skipOcr: "কোন রিপোর্ট নেই (এড়িয়ে যান)",
            captureBtn: "ছবি তুলুন",
            completionTitle: "মূল্যায়ন সম্পন্ন হয়েছে!",
            completionSub: "আপনি এই তথ্য কিভাবে সংরক্ষণ করতে চান নির্বাচন করুন:",
            choiceAccountOnlyTitle: "কেবল আমার স্বাস্থ্য অ্যাকাউন্টে (ABHA) সংরক্ষণ করুন",
            choiceAccountOnlyDesc: "রিপোর্টটি আপনার ডিজিটাল লকারে সংরক্ষিত হবে।",
            choiceParchiTitle: "অ্যাকাউন্টে সংরক্ষণ করুন এবং ডিজিটাল ওপিডি টোকেন তৈরি করুন",
            choiceParchiDesc: "হাসপাতালে লাইভ লাইনের জন্য টোকেন এবং রুম নম্বর তৈরি হবে।",
            proceedBtn: "এগিয়ে যান ➔",
            selectHospitalTitle: "আপনি বর্তমানে কোন হাসপাতালে আছেন?",
            selectHospitalSub: "সংযুক্ত নেটওয়ার্ক হাসপাতালগুলি থেকে আপনার হাসপাতাল নির্বাচন করুন:",
            confirmHospitalBtn: "হাসপাতাল নির্বাচন করুন এবং টোকেন তৈরি করুন ➔",
            parchiSuccess: "রেজিস্ট্রেশন সফল! আপনার ওপিডি স্লিপ গ্রহণ করুন",
            parchiWait: "নির্দিষ্ট রুমের বাইরে অনুগ্রহ করে অপেক্ষা করুন।",
            tokenLabel: "আপনার টোকেন নম্বর",
            deptLabel: "বিভাগ",
            roomLabel: "রুম নম্বর",
            waitLabel: "আনুমানিক অপেক্ষার সময়",
            signedQrTag: "ডিজিটালি স্বাক্ষরিত নিরাপদ টোকেন",
            printBtn: "স্লিপ প্রিন্ট করুন",
            homeBtn: "সমাপ্ত করুন ➔"
        },
        ta: {
            appName: "மெடிகியோஸ்க்",
            hospitalName: "அகில இந்திய ஆயுர்வேத நிறுவனம் மற்றும் மருத்துவமனைகள்",
            govtTag: "ஆயுஷ் அமைச்சகம் மற்றும் சுகாதார அமைச்சகம் • இந்திய அரசு",
            contrast: "அதிக மாறுபாடு",
            textSize: "எழுத்து அளவு",
            soundOn: "ஒலி ஆன்",
            soundOff: "ஒலி அமைதி",
            repeatQuestion: "கேள்வியை மீண்டும் கேட்கவும்",
            slowSpeech: "மெதுவான பேச்சு",
            needMoreTime: "கூடுதல் நேரம் தேவை",
            emergencyHelp: "அவசர உதவி",
            authTitle: "நோயாளி உள்நுழைவு & பதிவு",
            authSub: "ஆலோசனை பெற உங்கள் அடையாளத்தை உறுதிப்படுத்தவும்",
            abhaLoginBtn: "ஆபா (ABHA) ஐடி உள்நுழைவு / பதிவு",
            phoneLoginBtn: "மொபைல் எண் & எம்பிஐஎன்",
            walkinBtn: "விரைவான வாக்-இன் டோக்கன்",
            walkinSub: "நேரடியாக ஓபிடி ஆலோசனையைத் தொடங்கவும்",
            abhaCardScan: "ஆபா கார்டு ஸ்கேன்",
            enterPhonePlaceholder: "10 இலக்க மொபைல் எண்",
            enterNamePlaceholder: "நோயாளி பெயர்",
            startWalkinBtn: "தொடரவும் ➔",
            welcomePatient: "வணக்கம்",
            disciplineSelectTitle: "ஆலோசனை முறையைத் தேர்ந்தெடுக்கவும்",
            disciplineSelectSub: "அலோபதி அல்லது ஆயுர்வேதத்தைத் தேர்ந்தெடுக்கவும்",
            allopathyTitle: "நவீன மருத்துவம் (அலோபதி)",
            allopathyDesc: "பொது மருத்துவம், இதய நோய், எலும்பு முறிவு, தோல் நோய்.",
            allopathyBadge: "SOCRATES நெறிமுறை",
            ayushTitle: "ஆயுர்வேதம் & ஆயுஷ் ஓபிடி",
            ayushDesc: "காயசிகிச்சை, பஞ்சகர்மா, சல்லிய தந்திரம்.",
            ayushBadge: "தசவித பரீக்ஷா நெறிமுறை",
            bodyMapTitle: "பாதிக்கப்பட்ட உடல் பகுதியைத் தேர்ந்தெடுக்கவும்",
            bodyMapSub: "வலி அல்லது அசௌகரியம் உள்ள பகுதியைத் தொடவும்",
            stepLabel: "படி",
            ofLabel: "/",
            speakOrTap: "மைக் மூலம் பேசவும் அல்லது கீழே உள்ள விருப்பங்களைத் தொடவும்",
            listening: "கேட்கிறது... பேசவும்",
            recordingDone: "பதிவு முடிந்தது",
            liveStreaming: "நேரலை பதிவு",
            prevBtn: "முந்தைய",
            nextBtn: "அடுத்தது ➔",
            confirmBtn: "உறுதி செய் ➔",
            ocrTitle: "பழைய மருந்து சீட்டு அல்லது பரிசோதனை அறிக்கை",
            ocrSub: "கேமராவின் முன் ஆவணத்தை வைக்கவும்",
            skipOcr: "அறிக்கை இல்லை (தவிர்)",
            captureBtn: "படம் எடுக்கவும்",
            completionTitle: "மதிப்பீடு முடிந்தது!",
            completionSub: "இந்த தகவலை எவ்வாறு சேமிக்க விரும்புகிறீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்:",
            choiceAccountOnlyTitle: "எனது சுகாதார கணக்கில் (ABHA) மட்டும் சேமிக்கவும்",
            choiceAccountOnlyDesc: "டிஜிட்டல் லாக்கரில் பாதுகாப்பாக சேமிக்கப்படும்.",
            choiceParchiTitle: "கணக்கில் சேமித்து டிஜிட்டல் ஓபிடி சீட்டு பெறவும்",
            choiceParchiDesc: "மருத்துவமனை வரிசைக்கான டோக்கன் மற்றும் அறை எண் வழங்கப்படும்.",
            proceedBtn: "தொடரவும் ➔",
            selectHospitalTitle: "நீங்கள் தற்போது எந்த மருத்துவமனையில் உள்ளீர்கள்?",
            selectHospitalSub: "இணைக்கப்பட்ட மருத்துவமனைகளில் ஒன்றைத் தேர்ந்தெடுக்கவும்:",
            confirmHospitalBtn: "மருத்துவமனையைத் தேர்வு செய்து சீட்டு பெறவும் ➔",
            parchiSuccess: "பதிவு வெற்றிகரமானது! டோக்கன் சீட்டைப் பெறவும்",
            parchiWait: "குறிப்பிட்ட அறைக்கு வெளியே காத்திருக்கவும்.",
            tokenLabel: "உங்கள் டோக்கன் எண்",
            deptLabel: "துறை",
            roomLabel: "அறை எண்",
            waitLabel: "மதிப்பிடப்பட்ட காத்திருப்பு நேரம்",
            signedQrTag: "டிஜிட்டல் கையொப்பமிட்ட டோக்கன்",
            printBtn: "சீட்டை அச்சிடுக",
            homeBtn: "முகப்புக்குச் செல் ➔"
        },
        te: {
            appName: "మెడికియోస్క్",
            hospitalName: "ఆల్ ఇండియా ఇన్స్టిట్యూట్ ఆఫ్ ఆయుర్వేద మరియు ఆసుపత్రులు",
            govtTag: "ఆయుష్ మంత్రిత్వ శాఖ • భారత ప్రభుత్వం",
            contrast: "హై కాంట్రాస్ట్",
            textSize: "టెక్స్ట్ సైజు",
            soundOn: "సౌండ్ ఆన్",
            soundOff: "మ్యూట్",
            repeatQuestion: "ప్రశ్న మళ్ళీ వినండి",
            slowSpeech: "నెమ్మది స్పీచ్",
            needMoreTime: "మరింత సమయం కావాలి",
            emergencyHelp: "అత్యవసర సహాయం",
            authTitle: "రోగి లాగిన్ మరియు నమోదు",
            authSub: "సంప్రదింపు ప్రారంభించడానికి మీ వివరాలను నమోదు చేయండి",
            abhaLoginBtn: "ఆభా (ABHA) IDతో లాగిన్ / నమోదు",
            phoneLoginBtn: "మొబైల్ నంబర్ మరియు MPIN",
            walkinBtn: "త్వరిత వాక్-ఇన్ టోకెన్",
            walkinSub: "నేరుగా ఓపీడీ సంప్రదింపులను ప్రారంభించండి",
            abhaCardScan: "ఆభా కార్డు స్కాన్ చేయండి",
            enterPhonePlaceholder: "10 అంకెల మొబైల్ నంబర్",
            enterNamePlaceholder: "రోగి పూర్తి పేరు",
            startWalkinBtn: "కొనసాగించండి ➔",
            welcomePatient: "స్వాగతం",
            disciplineSelectTitle: "మీ సంప్రదింపు వ్యవస్థను ఎంచుకోండి",
            disciplineSelectSub: "అలోపతి లేదా ఆయుర్వేదం ఎంచుకోండి",
            allopathyTitle: "ఆధునిక వైద్యం (అలోపతి)",
            allopathyDesc: "జనరల్ మెడిసిన్, కార్డియాలజీ, ఆర్థోపెడిక్స్, డెర్మటాలజీ.",
            allopathyBadge: "SOCRATES ప్రోటోకాల్",
            ayushTitle: "ఆయుర్వేదం & ఆయుష్ ఓపీడీ",
            ayushDesc: "కాయచికిత్స, పంచకర్మ, శల్య తంత్రం.",
            ayushBadge: "దశవిధ పరీక్ష ప్రోటోకాల్",
            bodyMapTitle: "బాధిత శరీర భాగాన్ని ఎంచుకోండి",
            bodyMapSub: "నొప్పి ఉన్న శరీర భాగాన్ని తాకండి",
            stepLabel: "దశ",
            ofLabel: "/",
            speakOrTap: "మైక్‌లో మాట్లాడండి లేదా కింద ఉన్న ఎంపికలను తాకండి",
            listening: "వింటున్నాము... మాట్లాడండి",
            recordingDone: "రికార్డింగ్ పూర్తయింది",
            liveStreaming: "లైవ్ స్ట్రీమింగ్",
            prevBtn: "మునుపటిది",
            nextBtn: "తదుపరి ➔",
            confirmBtn: "నిర్ధారించండి ➔",
            ocrTitle: "పాత ప్రిస్క్రిప్షన్ లేదా ల్యాబ్ రిపోర్ట్ స్కాన్ చేయండి",
            ocrSub: "పత్రాన్ని కెమెరా ముందు ఉంచండి",
            skipOcr: "రిపోర్టులు లేవు (దాటవేయి)",
            captureBtn: "ఫోటో తీయండి",
            completionTitle: "మూల్యాంకనం పూర్తయింది!",
            completionSub: "మీరు ఈ సమాచారాన్ని ఎలా సేవ్ చేయాలనుకుంటున్నారో ఎంచుకోండి:",
            choiceAccountOnlyTitle: "నా హెల్త్ ఖాతాలో (ABHA) మాత్రమే సేవ్ చేయండి",
            choiceAccountOnlyDesc: "డిజిటల్ లాకర్‌లో భద్రపరచబడుతుంది.",
            choiceParchiTitle: "ఖాతాలో సేవ్ చేసి డిజిటల్ ఓపీడీ టోకెన్ పొందండి",
            choiceParchiDesc: "ఆసుపత్రి క్యూ కోసం టోకెన్ మరియు గది నంబర్ జారీ చేయబడుతుంది.",
            proceedBtn: "కొనసాగించండి ➔",
            selectHospitalTitle: "మీరు ప్రస్తుతం ఏ ఆసుపత్రిలో ఉన్నారు?",
            selectHospitalSub: "కనెక్ట్ చేయబడిన ఆసుపత్రుల నుండి మీ ఆసుపత్రిని ఎంచుకోండి:",
            confirmHospitalBtn: "ఆసుపత్రిని ఎంచుకుని టోకెన్ పొందండి ➔",
            parchiSuccess: "నమోదు విజయవంతమైంది! మీ ఓపీడీ స్లిప్ తీసుకోండి",
            parchiWait: "దయచేసి మీ గది వెలుపల వేచి ఉండండి.",
            tokenLabel: "మీ టోకెన్ నంబర్",
            deptLabel: "విభాగం",
            roomLabel: "గది నంబర్",
            waitLabel: "వేచి ఉండే సమయం",
            signedQrTag: "డిజిటల్ సంతకం చేసిన టోకెన్",
            printBtn: "స్లిప్ ప్రింట్ చేయండి",
            homeBtn: "ముగించు ➔"
        },
        mr: {
            appName: "मेडीकियोस्क",
            hospitalName: "अखिल भारतीय आयुर्वेद संस्थान आणि संलग्न रुग्णालये",
            govtTag: "आयुष मंत्रालय • भारत सरकार",
            contrast: "हाय कॉन्ट्रास्ट",
            textSize: "अक्षर आकार",
            soundOn: "आवाज चालू",
            soundOff: "आवाज बंद",
            repeatQuestion: "प्रश्न पुन्हा ऐका",
            slowSpeech: "हळू आवाज",
            needMoreTime: "आणखी वेळ हवा आहे",
            emergencyHelp: "तातडीची मदत",
            authTitle: "रुग्ण लॉगिन आणि नोंदणी",
            authSub: "तपासणी सुरू करण्यासाठी आपली ओळख नोंदवा",
            abhaLoginBtn: "आभा (ABHA) आयडीने लॉगिन / नोंदणी",
            phoneLoginBtn: "मोबाईल नंबर आणि एमपिन",
            walkinBtn: "त्वरित वॉक-इन पावती",
            walkinSub: "कोणत्याही आयडीशिवाय थेट ओपीडी सुरू करा",
            abhaCardScan: "आभा कार्ड स्कॅन करा",
            enterPhonePlaceholder: "१० अंकी मोबाईल नंबर",
            enterNamePlaceholder: "रुग्णाचे पूर्ण नाव",
            startWalkinBtn: "पुढे जा ➔",
            welcomePatient: "स्वागत आहे",
            disciplineSelectTitle: "आपली सल्लामसलत प्रणाली निवडा",
            disciplineSelectSub: "आधुनिक औषधोपचार किंवा आयुर्वेद ओपीडी निवडा",
            allopathyTitle: "आधुनिक औषधोपचार (अ‍ॅलोपॅथी)",
            allopathyDesc: "जनरल मेडिसिन, हृदयरोग, अस्थिरोग आणि त्वचारोग.",
            allopathyBadge: "SOCRATES प्रोटोकॉल",
            ayushTitle: "आयुर्वेद आणि आयुष ओपीडी",
            ayushDesc: "कायाचिकित्सा, पंचकर्म, शल्य तंत्र आणि अग्नी चिकित्सा.",
            ayushBadge: "दशविध परीक्षा प्रोटोकॉल",
            bodyMapTitle: "त्रासाचा मुख्य अवयव निवडा",
            bodyMapSub: "वेदना असलेल्या शरीराच्या भागावर स्पर्श करा",
            stepLabel: "टप्पा",
            ofLabel: "/",
            speakOrTap: "माईकवर बोला किंवा खालील पर्याय निवडा",
            listening: "ऐकत आहोत... बोला",
            recordingDone: "रेकॉर्डिंग पूर्ण",
            liveStreaming: "थेट रेकॉर्डिंग",
            prevBtn: "मागे",
            nextBtn: "पुढे ➔",
            confirmBtn: "पुष्टी करा ➔",
            ocrTitle: "जुनी चिठ्ठी किंवा तपासणी अहवाल स्कॅन करा",
            ocrSub: "कागदपत्र कॅमेऱ्यासमोर धरा",
            skipOcr: "काहीही नाही (पुढे जा)",
            captureBtn: "फोटो काढा",
            completionTitle: "मूल्यांकन पूर्ण झाले!",
            completionSub: "माहिती कशी सेव्ह करायची आहे ते निवडा:",
            choiceAccountOnlyTitle: "फक्त माझ्या आरोग्य खात्यात (ABHA) सेव्ह करा",
            choiceAccountOnlyDesc: "डिजिटल लॉकरमध्ये सुरक्षित राहील.",
            choiceParchiTitle: "खात्यात सेव्ह करा आणि डिजिटल ओपीडी पावती मिळवा",
            choiceParchiDesc: "रुग्णालयातील रांगेसाठी टोकन आणि खोली क्रमांक दिला जाईल.",
            proceedBtn: "पुढे जा ➔",
            selectHospitalTitle: "आपण सध्या कोणत्या रुग्णालयात आहात?",
            selectHospitalSub: "संलग्न रुग्णालयांमधून आपले रुग्णालय निवडा:",
            confirmHospitalBtn: "रुग्णालय निवडा आणि पावती मिळवा ➔",
            parchiSuccess: "नोंदणी यशस्वी! आपली ओपीडी पावती घ्या",
            parchiWait: "कृपया नियुक्त खोलीबाहेर प्रतीक्षा करा.",
            tokenLabel: "आपला टोकन क्रमांक",
            deptLabel: "विभाग",
            roomLabel: "खोली क्रमांक",
            waitLabel: "अंदाजे प्रतीक्षा वेळ",
            signedQrTag: "डिजिटल स्वाक्षरी असलेले टोकन",
            printBtn: "पावती प्रिंट करा",
            homeBtn: "समाप्त करा ➔"
        },
        gu: {
            appName: "મેડિકિઓસ્ક",
            hospitalName: "ઓલ ઇન્ડિયા ઇન્સ્ટિટ્યૂટ ઓફ આયુર્વેદ અને સંલગ્ન હોસ્પિટલો",
            govtTag: "આયુષ મંત્રાલય • ભારત સરકાર",
            contrast: "હાઇ કોન્ટ્રાસ્ટ",
            textSize: "અક્ષર કદ",
            soundOn: "અવાજ ચાલુ",
            soundOff: "અવાજ બંધ",
            repeatQuestion: "પ્રશ્ન ફરીથી સાંભળો",
            slowSpeech: "ધીમો અવાજ",
            needMoreTime: "વધુ સમય જોઈએ છે",
            emergencyHelp: "ઇમરજન્સી સહાય",
            authTitle: "દર્દી લૉગિન અને નોંધણી",
            authSub: "તપાસ શરૂ કરવા માટે તમારી ઓળખ ચકાસો",
            abhaLoginBtn: "આભા (ABHA) આઈડીથી લૉગિન / નોંધણી",
            phoneLoginBtn: "મોબાઇલ નંબર અને એમપિન",
            walkinBtn: "ઝડપી વૉક-ઇન પાવતી",
            walkinSub: "કોઈપણ આઈડી વગર તરત જ ઓપીડી શરૂ કરો",
            abhaCardScan: "આભા કાર્ડ સ્કેન કરો",
            enterPhonePlaceholder: "૧૦ અંકનો મોબાઇલ નંબર",
            enterNamePlaceholder: "દર્દીનું પૂરું નામ",
            startWalkinBtn: "આગળ વધો ➔",
            welcomePatient: "સ્વાગત છે",
            disciplineSelectTitle: "તમારી કન્સલ્ટેશન સિસ્ટમ પસંદ કરો",
            disciplineSelectSub: "એલોપેથી અથવા આયુર્વેદ ઓપીડી પસંદ કરો",
            allopathyTitle: "આધુનિક દવા (એલોપેથી)",
            allopathyDesc: "જનરલ મેડિસિન, કાર્ડિયોલોજી, ઓર્થોપેડિક્સ, ચર્મરોગ.",
            allopathyBadge: "SOCRATES પ્રોટોકોલ",
            ayushTitle: "આયુર્વેદ અને આયુષ ઓપીડી",
            ayushDesc: "કાયાચિકિત્સા, પંચકર્મ, શલ્ય તંત્ર અને અગ્નિ ચિકિત્સા.",
            ayushBadge: "દશવિધ પરીક્ષા પ્રોટોકોલ",
            bodyMapTitle: "તકલીફનો મુખ્ય ભાગ પસંદ કરો",
            bodyMapSub: "દુખાવો હોય તે શરીરના અંગ પર સ્પર્શ કરો",
            stepLabel: "પગલું",
            ofLabel: "/",
            speakOrTap: "માઇક પર બોલો અથવા નીચે આપેલા વિકલ્પો પસંદ કરો",
            listening: "સાંભળી રહ્યા છીએ... બોલો",
            recordingDone: "રેકોર્ડિંગ પૂર્ણ",
            liveStreaming: "લાઇવ રેકોર્ડિંગ",
            prevBtn: "પાછળ",
            nextBtn: "આગળ ➔",
            confirmBtn: "પુષ્ટિ કરો ➔",
            ocrTitle: "જૂની દવા પાવતી અથવા રિપોર્ટ સ્કેન કરો",
            ocrSub: "દસ્તાવેજ કૅમેરાની સામે રાખો",
            skipOcr: "કોઈ રિપોર્ટ નથી (આગળ વધો)",
            captureBtn: "ફોટો પાડો",
            completionTitle: "તપાસ પૂર્ણ થઈ ગઈ છે!",
            completionSub: "તમે આ માહિતી કેવી રીતે સાચવવા માંગો છો તે પસંદ કરો:",
            choiceAccountOnlyTitle: "ફક્ત મારા આરોગ્ય ખાતામાં (ABHA) સાચવો",
            choiceAccountOnlyDesc: "ડિજિટલ લૉકરમાં સુરક્ષિત રહેશે.",
            choiceParchiTitle: "ખાતામાં સાચવો અને ડિજિટલ ઓપીડી પાવતી બનાવો",
            choiceParchiDesc: "હોસ્પિટલ કતાર માટે ટોકન અને રૂમ નંબર જારી થશે.",
            proceedBtn: "આગળ વધો ➔",
            selectHospitalTitle: "તમે હાલમાં કઈ હોસ્પિટલમાં છો?",
            selectHospitalSub: "જોડાયેલ હોસ્પિટલોમાંથી તમારી હોસ્પિટલ પસંદ કરો:",
            confirmHospitalBtn: "હોસ્પિટલ પસંદ કરો અને પાવતી બનાવો ➔",
            parchiSuccess: "નોંધણી સફળ! તમારી ઓપીડી પાવતી મેળવો",
            parchiWait: "નિયુક્ત રૂમની બહાર કૃપા કરીને રાહ જુઓ.",
            tokenLabel: "તમારો ટોકન નંબર",
            deptLabel: "વિભાગ",
            roomLabel: "રૂમ નંબર",
            waitLabel: "અંદાજિત રાહ જોવાનો સમય",
            signedQrTag: "ડિજિટલ સહી થયેલ ટોકન",
            printBtn: "પાવતી પ્રિન્ટ કરો",
            homeBtn: "સમાપ્ત કરો ➔"
        }
    }
};

export function getTranslation(lang = "hi") {
    return CONFIG.I18N[lang] || CONFIG.I18N.hi;
}
